/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	printf("Size of a char is %u byte\n", sizeof(char));
	printf("Size of a short is %u byte\n", sizeof(short));
	printf("Size of a int is %u byte\n", sizeof(int));
	printf("Size of a long is %u byte\n", sizeof(long));
	printf("Size of a long long is %u byte\n", sizeof(long long));
	printf("Size of a float is %u byte\n", sizeof(float));
	printf("Size of a double is %u byte\n", sizeof(double));
	for(;;);
}
